/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author brau
 */
package brau.db2.memoria;

import org.taqque.memoriaintermedia.GestorMemoriaIntermedia;
import org.taqque.memoriaintermedia.Pagina;
import java.util.LinkedList;
import java.lang.*;

/**
 *
 * @author User
 */
public class InnerJoin extends javax.swing.JFrame {
    GestorMemoriaIntermedia gestor = new GestorMemoriaIntermedia(25);
    LinkedList<Prestatario>  TPrestatario = new LinkedList<Prestatario>();
    LinkedList<Cliente>  TCliente = new LinkedList<Cliente>();
    LinkedList<Object> Resultado = new LinkedList<Object>();


    /** Creates new form InnerJoin */
    public InnerJoin() {
        initComponents();
        cbTablaI.setVisible(false);
        cbAtributo.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        TPrestatario.add(new Prestatario("Fulano Mengano", 12345678));
        TPrestatario.add(new Prestatario("Loreem Ipsum", 91234567));
        TPrestatario.add(new Prestatario("John Smith", 89123456));
        TPrestatario.add(new Prestatario("Juan Perez", 78912345));
        TPrestatario.add(new Prestatario("Wicho Garcia", 67891234));
        TPrestatario.add(new Prestatario("Heath Bleazard", 56789123));

        TCliente.add(new Cliente("Maria Savedra Zuñiga", 12345678));
        TCliente.add(new Cliente("Christian Soto Bueno", 91234567));
        TCliente.add(new Cliente("Aydeé Sosa Arriola", 89123456));
        TCliente.add(new Cliente("Miriam Alegía Zevallos", 78912345));
        TCliente.add(new Cliente("Wilfredo Marquez Boza", 67891234));
        TCliente.add(new Cliente("Kelly Medrano Ñuflo", 56789123));
        
        cbTabla.removeAllItems();
        cbOperacion.removeAllItems();
        cbTablaI.removeAllItems();
        cbAtributo.removeAllItems();

        cbTabla.addItem("TPrestatario");
        cbTablaI.addItem("TPrestatario");
        cbTablaI.addItem("TCliente");
        cbTabla.addItem("TCliente");


        cbOperacion.addItem("Inner Join");
        cbAtributo.addItem("Nombre");
        cbAtributo.addItem("DNI");
        MostrarTabla();        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbTabla = new javax.swing.JComboBox();
        cbOperacion = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        cbTablaI = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cbAtributo = new javax.swing.JComboBox();
        btnResultado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccionar tabla:");

        jLabel2.setText("Seleccionar operacion:");

        cbTabla.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTabla.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                change2(evt);
            }
        });

        cbOperacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbOperacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                changed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setText("Inner join con la tabla:");

        cbTablaI.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Sobre el atributo");

        cbAtributo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnResultado.setText("Resultado");
        btnResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(32, 32, 32)
                                .addComponent(cbTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbTablaI, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cbOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbTablaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cbAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResultado))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void changed(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_changed

    cbTablaI.setVisible(true);
    cbAtributo.setVisible(true);
    jLabel3.setVisible(true);
    jLabel4.setVisible(true);
    
}//GEN-LAST:event_changed

private void change2(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_change2
    if (cbTabla.getSelectedItem() == "TPrestatario") {
        cbTablaI.removeAllItems();
        cbTablaI.addItem("TCliente");
    } else if (cbTabla.getSelectedItem() == "TCliente") {
        cbTablaI.removeAllItems();
        cbTablaI.addItem("TPrestatario");
    }    
}//GEN-LAST:event_change2

private void btnResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadoActionPerformed
    InnerJoin(cbAtributo.getSelectedItem());
}//GEN-LAST:event_btnResultadoActionPerformed
 
private void InnerJoin(Object atributo)
{
    int i = 0;
    int j = 0;
    for (Prestatario prestatario : TPrestatario) {
        Pagina pag = new Pagina(i, prestatario);
        gestor.ponerPaginaEnBuffer(pag);
        i++;
    }
    
    //colocar clientes 
    for (Cliente cliente : TCliente) {
        Pagina pag = new Pagina(j,cliente);
       // buscar la pagina actual en el buffer
        Pagina[] buffer = gestor.getBuffer();
        for (int k = 0; k < buffer.length; k++) {
            if (buffer[k]!= null) {
               Object p= buffer[k].getDatos();
                if (p.equals(pag.getDatos()) ) {
                  //Escribirlo
                   textArea.setText(textArea.getText() + pag.getDatos() + "\n");
                }
            } else {
                break;
            }
        }
        gestor.ponerPaginaEnBuffer(pag);
        j++;
    }
}
/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(InnerJoin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(InnerJoin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(InnerJoin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(InnerJoin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {

        public void run() {
            new InnerJoin().setVisible(true);
        }
    });
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResultado;
    private javax.swing.JComboBox cbAtributo;
    private javax.swing.JComboBox cbOperacion;
    private javax.swing.JComboBox cbTabla;
    private javax.swing.JComboBox cbTablaI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables

    private void MostrarTabla() {
        //mostrar siempre el resultado
        textArea.setText("");
        for (Object o : Resultado) {
            textArea.setText(textArea.getText() + o.toString()+"\n");           
        }        
    }
    
    
}
