/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.taqque.almacenamiento;

import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author brau
 */
public class CatalogoTarea2 extends javax.swing.JFrame {

    /**
     * Creates new form CatalogoTarea2
     */
    private DefaultTableModel theModel;
    private ArrayList<Atributo> metadata = new ArrayList<Atributo>();
    private Catalogo catalogo = new Catalogo(EntradaCatalogo.TAQQUE_DIR+
                    System.getProperty("file.separator") + "catalogotarea.dat");
    
    public CatalogoTarea2() {
        initComponents();
        setTypes();
        theModel = (DefaultTableModel) atributos.getModel();
        tabla.requestFocusInWindow();
        updateNumTables();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabla = new javax.swing.JTextField();
        tablaLabel = new javax.swing.JLabel();
        panel = new javax.swing.JScrollPane();
        atributos = new javax.swing.JTable();
        agregarCatalogo = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        agregar = new javax.swing.JButton();
        quitar = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();
        guardar = new javax.swing.JButton();
        tablasLabel = new javax.swing.JLabel();
        numeroTablas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tablaLabel.setText("Nombre de la tabla:");

        atributos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        atributos.setColumnSelectionAllowed(true);
        atributos.getTableHeader().setReorderingAllowed(false);
        panel.setViewportView(atributos);
        atributos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        agregarCatalogo.setText("Agregar al catálogo");
        agregarCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCatalogoActionPerformed(evt);
            }
        });

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        agregar.setText("Agregar fila");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        quitar.setText("Quitar fila");
        quitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarActionPerformed(evt);
            }
        });

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        tablasLabel.setText("Tablas en el catálogo:");

        numeroTablas.setText("numero");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(tablaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(agregarCatalogo)
                                .addGap(18, 18, 18)
                                .addComponent(guardar)
                                .addGap(11, 11, 11)
                                .addComponent(limpiar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(agregar)
                .addGap(18, 18, 18)
                .addComponent(quitar)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(separator)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tablasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroTablas)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tablaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar)
                    .addComponent(quitar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tablasLabel)
                    .addComponent(numeroTablas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarCatalogo)
                    .addComponent(limpiar)
                    .addComponent(guardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        theModel.addRow(new Object[2]);
    }//GEN-LAST:event_agregarActionPerformed

    private void quitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarActionPerformed
        int selected = atributos.getSelectedRow();
        if(selected >= 0) {
            theModel.removeRow(selected);
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona una fila");
        }
    }//GEN-LAST:event_quitarActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        clear();
    }//GEN-LAST:event_limpiarActionPerformed

    private void agregarCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCatalogoActionPerformed
        if(theModel.getRowCount() < 1){
            JOptionPane.showMessageDialog(this, "Ingresa al menos un campo");
        } else if(tabla.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingresa el nombre de la tabla");
            tabla.requestFocusInWindow();
        } else {
            for(int i = 0; i < theModel.getRowCount(); i++) {
                String nombre = theModel.getValueAt(i, 0).toString();
                String tipo = theModel.getValueAt(i, 1).toString();
                Class<? extends Comparable> tipoClass = null;

                if(tipo.equals("String")) {
                    tipoClass = String.class;
                } else if(tipo.equals("Integer")) {
                    tipoClass = Integer.class;
                } else if(tipo.equals("Float")) {
                    tipoClass = Float.class;
                }
                metadata.add(new Atributo(nombre, tipoClass));
            }

            Tabla t = new Tabla(tabla.getText(), metadata);

            EntradaCatalogo entrada = new EntradaCatalogo(t);

            catalogo.crearNuevaEntrada(entrada);
            updateNumTables();

            System.out.println(catalogo);

            clear();            
        }
    }//GEN-LAST:event_agregarCatalogoActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        try {
            catalogo.escribirCatalogo();
        } catch(Exception e) {
            System.err.println(e.toString());
        }
        
        System.out.println(catalogo);
    }//GEN-LAST:event_guardarActionPerformed

    private void setTypes() {
        TableColumn tipo = atributos.getColumnModel().getColumn(1);
        JComboBox combo = new JComboBox();
        combo.addItem("String");
        combo.addItem("Integer");
        combo.addItem("Float");
        tipo.setCellEditor(new DefaultCellEditor(combo));
    }
    
    private void clear() {
        theModel.setRowCount(0);
        metadata.clear();
        tabla.setText("");
        tabla.requestFocusInWindow();
    }
    
    private void updateNumTables() {
        numeroTablas.setText(String.valueOf(catalogo.getNumeroDeTablas()));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatalogoTarea2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatalogoTarea2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatalogoTarea2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatalogoTarea2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CatalogoTarea2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JButton agregarCatalogo;
    private javax.swing.JTable atributos;
    private javax.swing.JButton guardar;
    private javax.swing.JButton limpiar;
    private javax.swing.JLabel numeroTablas;
    private javax.swing.JScrollPane panel;
    private javax.swing.JButton quitar;
    private javax.swing.JSeparator separator;
    private javax.swing.JTextField tabla;
    private javax.swing.JLabel tablaLabel;
    private javax.swing.JLabel tablasLabel;
    // End of variables declaration//GEN-END:variables
}
